#!/bin/bash
GREEN='\033[1;32m'
RED='\033[0;31m'
ENDCOLOR='\033[0m'

function set_common_mysql_rmitcas_env{
   #common settings
   cp -v options/db/mysql/docker-compose.yml .
   cp -v options/db/mysql/Makefile .
   cp -v options/db/mysql/docker_settings.py mytardis-portal/mytardis_settings/
}

if [ "$#" -eq 0 ] || [ "$1" == "postgres" ]; then
   echo  -e "${GREEN}Preparing docker environment to install postgres db${ENDCOLOR}"
   cp -v options/db/postgres/Makefile .
   cp -v options/db/postgres/docker-compose.yml .
   cp -v options/db/postgres/docker_settings.py mytardis-portal/mytardis_settings/
   cp -v options/db/postgres/Dockerfile mytardis-portal/
   cp -v options/db/postgres/docker-compose-published.yml . 
   cp -v options/db/postgres/Dockerfile-published mytardis-portal/
   echo postgres > tag.txt
   echo "Done" && printf "\n"

elif [ "$1" == "rmitcas" ] || [ "$1" == "mysql" ]; then
   if [ "$1" == "rmitcas" ]; then
   	echo -e "${GREEN}Preparing docker environment to install RMIT CAS authentication with MySQL db${ENDCOLOR} "
        set_common_mysql_rmitcas_env
        cp -v options/auth/rmitcas/docker-compose-published.yml
 	cat options/auth/rmitcas/docker_settings.py >> mytardis-portal/mytardis_settings/docker_settings.py
        echo "'cat options/auth/rmitcas/docker_settings.py >> mytardis-portal/mytardis_settings/docker_settings.py'"
        cp -v options/auth/rmitcas/Dockerfile mytardis-portal/
        cp -v options/auth/rmitcas/Dockerfile-published mytardis-portal/
        echo rmitcas > tag.txt

    else
        echo -e "${GREEN}Preparing docker environment to install MySQL db${ENDCOLOR}"
    	set_common_mysql_rmitcas_env
        cp -v options/db/mysql/docker-compose-published.yml .
   	cp -v options/db/mysql/Dockerfile mytardis-portal/
   	cp -v options/db/mysql/Dockerfile-published mytardis-portal/
   	echo mysql > tag.txt
    fi
    echo "Done" && printf "\n"

else
  echo -e "${RED}Invalid command: $0 $@ ${ENDCOLOR}"
  echo "Valid commands: "
  echo "  init"
  echo "  init postgres"
  echo "  init mysql"
  echo "  init rmitcas"

fi
