#!/bin/bash
GREEN='\033[1;32m'
RED='\033[0;31m'
ENDCOLOR='\033[0m'

if [ "$#" -eq 0 ] || [ "$1" == "postgres" ]; then
   echo  -e "${GREEN}Preparing docker environment to install postgres db${ENDCOLOR}"
   cp -v options/db/postgres/Makefile .
   cp -v options/db/postgres/docker-compose.yml .
   cp -v options/db/postgres/docker_settings.py mytardis-portal/mytardis_settings/
   mkdir -p mytardis-portal-published/mytardis_settings
   cp -v options/db/postgres/docker_settings.py mytardis-portal-published/mytardis_settings/
   cp -v options/db/postgres/Dockerfile mytardis-portal/
   cp -v options/db/postgres/docker-compose-published.yml . 
   cp -v options/db/postgres/Dockerfile-published mytardis-portal-published/Dockerfile
   echo postgres > tag.txt
   echo "Done" && printf "\n"

elif [ "$1" == "rmitcas" ]; then
   echo -e "${GREEN}Preparing docker environment to install RMIT CAS authentication with MySQL db${ENDCOLOR} "
   cp -v options/db/mysql/Makefile .
   cp -v options/auth/rmitcas/docker-compose.yml .
   cp -v options/auth/rmitcas/docker-compose-published.yml . 
   cp -v options/db/mysql/docker_settings.py mytardis-portal/mytardis_settings/
   cat options/auth/rmitcas/docker_settings.py >> mytardis-portal/mytardis_settings/docker_settings.py
   echo "'cat options/auth/rmitcas/docker_settings.py >> mytardis-portal/mytardis_settings/docker_settings.py'"
   mkdir -p mytardis-portal-published/mytardis_settings
   cp -v mytardis-portal/mytardis_settings/docker_settings.py  mytardis-portal-published/mytardis_settings/
   cp -v options/auth/rmitcas/Dockerfile mytardis-portal/
   cp -v options/auth/rmitcas/Dockerfile-published mytardis-portal-published/Dockerfile
   #cp -v options/db/mysql/Dockerfile-published mytardis-portal-published/Dockerfile
   cp -v options/db/mysql/generate_secret_key.sh mytardis-portal-published/
   echo rmitcas > tag.txt
   echo "Done" && printf "\n"

elif [ "$1" == "mysql" ]; then
   echo -e "${GREEN}Preparing docker environment to install MySQL db${ENDCOLOR}"
   cp -v options/db/mysql/Makefile .
   cp -v options/db/mysql/docker-compose.yml .
   cp -v options/db/mysql/docker-compose-published.yml .
   cp -v options/db/mysql/docker_settings.py mytardis-portal/mytardis_settings/
   mkdir -p mytardis-portal-published/mytardis_settings
   cp -v options/db/mysql/docker_settings.py mytardis-portal-published/mytardis_settings/
   cp -v options/db/mysql/Dockerfile mytardis-portal/
   cp -v options/db/mysql/Dockerfile-published mytardis-portal-published/Dockerfile
   cp -v options/db/mysql/generate_secret_key.sh mytardis-portal-published/
   echo mysql > tag.txt
   echo "Done" && printf "\n"

else
  echo -e "${RED}Invalid command: $0 $@ ${ENDCOLOR}"
  echo "Valid commands: "
  echo "  init"
  echo "  init postgres"
  echo "  init mysql"
  echo "  init rmitcas"

fi
