FROM        iiman/dockermytardis_mytardis:postgres

MAINTAINER  Ian Thomas <iantedwardthomas@gmail.com> and Iman Yusuf <iimanyusuf@gmail.com>

USER root

ADD mytardis_settings/ /mytardis_settings

VOLUME /mytardis_settings
